### ISSUE TITLE
 Incompatible types "Address" and "<null>" for binary operator "!="

### ISSUE THREAD

**Issue by satyasai69** [ton-ion/tonion-contracts#16]
https://github.com/ton-ion/tonion-contracts/blob/57e84a223798db5a43ffe57250baa0928a288ff2/contracts/traits/tokens/jetton/JettonMaster.tact#L72

**Comment by satyasai69** [comment]
if (msg.response_destination.toString() != "")

**Comment by ZigBalthazar** [comment]
fixed #17
